services:
  sentry-api:
    image: sentry
    container_name: sentry-api
    platform: linux/amd64
    env_file:
      - .env
    depends_on:
      - db-sentry
      - redis
    ports:
      - "9000:9000"

  sentry-worker:
    image: sentry
    platform: linux/amd64
    env_file:
      - .env
    depends_on:
      - db-sentry
      - redis
    command: sentry run worker

  sentry-cron:
    image: sentry
    platform: linux/amd64
    env_file:
      - .env
    depends_on:
      - db-sentry
      - redis
    command: sentry run cron

  db-sentry:
    image: postgres:16
    environment:
      - POSTGRES_USER=sentry
      - POSTGRES_PASSWORD=sentry
      - POSTGRES_DB=sentry

  redis:
    image: redis:6.2.6
    container_name: redis
    restart: always
