version: '3'

x-env:
  &default-env
  env_file:
    - .env

services:

  database:
    image: postgres:16
    container_name: database
    <<: *default-env 
    volumes:
      - db_volume:/var/lib/postgresql/data
      - ./database/init_db.sql:/docker-entrypoint-initdb.d/init_data.sql
    restart: always
    healthcheck:
      test: [ "CMD", "pg_isready", "-d", "${POSTGRES_DB}", "-U", "${POSTGRES_USER}" ]
      interval: 15s
      timeout: 15s
      retries: 5

  elasticsearch:
    image: elasticsearch:8.6.2
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    volumes:
      - es_data:/usr/share/elasticsearch/data
    healthcheck:
      test: [ "CMD-SHELL", "curl localhost:9200" ]
      interval: 30s
      timeout: 30s
      retries: 3
    depends_on:
      - database

  redis:
    image: redis
    container_name: redis
    volumes:
      - redis_volume:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 30s
      timeout: 10s
      retries: 3

  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "16686:16686"
      - "14250:14250"
      - "14268:14268"
      - "14269:14269"
      - "9411:9411"

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    expose:
      - 8000
    ports:
      - "8000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - static_volume:/static
    depends_on:
      - database
      - backend

  nx_etl:
    build: nx_etl/
    container_name: nx_etl
    <<: *default-env
    restart: always
    depends_on:
      - database
      - redis
      - elasticsearch

  nx_backend:
    build:
      dockerfile: Dockerfile
      context: ./nx_backend
    container_name: nx_backend
    <<: *default-env 
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/api/openapi || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
    depends_on:
      - redis
      - elasticsearch
  
  nx_auth:
    build:
      dockerfile: Dockerfile
      context: ./nx_auth
    container_name: nx_auth
    <<: *default-env
    volumes:
      - ./nx_auth:/app
    depends_on:
      - database
      - redis

  ugc:
    build: nx_ugc/
    container_name: ugc
    <<: *default-env
    healthcheck:
      test: [ "CMD", "curl", "--fail", "http://localhost:5000/ping" ]
      interval: 30s
      timeout: 10s
      retries: 3

  backend:
    build: movies_admin/
    container_name: backend
    <<: *default-env
    restart: always
    healthcheck:
      test: [ "CMD", "curl", "--fail", "localhost:8000/admin" ]
      interval: 15s
      timeout: 15s
      retries: 5
    volumes:
      - static_volume:/opt/app/static

  kafka-ui:
    image: provectuslabs/kafka-ui:v0.7.0
    environment:
      - KAFKA_CLUSTERS_0_BOOTSTRAP_SERVERS=kafka-0:9092
      - KAFKA_CLUSTERS_0_NAME=kraft

  kafka-0:
    image: bitnami/kafka:3.4
    ports:
      - "9094:9094"
    environment:
      - KAFKA_ENABLE_KRAFT=yes
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka-0:9093,1@kafka-1:9093,2@kafka-2:9093
      - KAFKA_KRAFT_CLUSTER_ID=abcdefghijklmnopqrstuv
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka-0:9092,EXTERNAL://127.0.0.1:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
    volumes:
      - kafka_0_data:/bitnami/kafka

  kafka-1:
    image: bitnami/kafka:3.4
    ports:
      - "9095:9095"
    environment:
      - KAFKA_ENABLE_KRAFT=yes
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka-0:9093,1@kafka-1:9093,2@kafka-2:9093
      - KAFKA_KRAFT_CLUSTER_ID=abcdefghijklmnopqrstuv
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9095
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka-1:9092,EXTERNAL://127.0.0.1:9095
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
    volumes:
      - kafka_1_data:/bitnami/kafka

  kafka-2:
    image: bitnami/kafka:3.4
    ports:
      - "9096:9096"
    environment:
      - KAFKA_ENABLE_KRAFT=yes
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_NODE_ID=2
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka-0:9093,1@kafka-1:9093,2@kafka-2:9093
      - KAFKA_KRAFT_CLUSTER_ID=abcdefghijklmnopqrstuv
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9096
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka-2:9092,EXTERNAL://127.0.0.1:9096
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
    volumes:
      - kafka_2_data:/bitnami/kafka
    depends_on:
      - kafka-0
      - kafka-1
      - kafka-ui

  kafka-init:
    image: bitnami/kafka:3.4
    depends_on:
      - kafka-0
      - kafka-1
      - kafka-2
      - kafka-ui
      - ugc
    entrypoint: [ "/bin/sh", "-c" ]
    command: |
      "
      kafka-topics.sh --create --topic user --bootstrap-server kafka-0:9092 --partitions 3 --replication-factor 3 --config min.insync.replicas=2 || true
      kafka-topics.sh --create --topic film --bootstrap-server kafka-0:9092 --partitions 3 --replication-factor 3 --config min.insync.replicas=2 || true
      "

  consumer_film:
    build: kafka_clickhouse_etl/
    environment:
      - TOPIC=film
      - GROUP_ID=film
      - PYTHONUNBUFFERED=1
    # restart: always

  consumer_user:
    build: kafka_clickhouse_etl/
    environment:
      - TOPIC=user
      - GROUP_ID=user
      - PYTHONUNBUFFERED=1
    # restart: always

volumes:
  redis_volume:
  es_data:
  db_volume:
  static_volume:
  kafka_0_data:
  kafka_1_data:
  kafka_2_data: