version: "3.9"

services:

  elasticsearchELK:
    image: elasticsearch:8.10.2
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"

  logstash:
    image: logstash:8.10.2
    environment:
      - XPACK_MONITORING_ENABLED=false
      - ES_HOST=elasticsearchELK:9200
    ports:
      - "5044:5044/tcp"
    volumes:
      - ./logstash.conf:/config/logstash.conf:ro
    command: logstash -f /config/logstash.conf

  kibana:
    image: kibana:8.10.2
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearchELK
      - logstash
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearchELK:9200
