version: '3'

services:
  elasticsearch:
    image: elasticsearch:8.6.2
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
    volumes:
      - es_data:/usr/share/elasticsearch/data
    healthcheck:
      test: [ "CMD-SHELL", "curl localhost:9200" ]
      interval: 30s
      timeout: 30s
      retries: 1

  redis:
    image: redis
    container_name: redis
    volumes:
      - redis_volume:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 30s
      timeout: 10s
      retries: 3

  app:
    build:
      dockerfile:  Dockerfile
      context: ./nx_backend
    container_name: app
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/api/openapi || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
    depends_on:
      redis:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy

  frontend:
    image: nginx:latest
    container_name: frontend
    expose:
      - 8000
    ports:
      - "8000:80"
    volumes:
      - ./nx_frontend/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nx_frontend/configs:/etc/nginx/conf.d:ro
      - static_volume:/static
    restart: always
    depends_on:
      app:
        condition: service_healthy

volumes:
  static_volume:
  redis_volume:
  es_data: