"""init

Revision ID: ddd9ceb4072d
Revises:
Create Date: 2025-04-30 13:57:49.764155

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ddd9ceb4072d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE SCHEMA IF NOT EXISTS events_admin")
    op.create_table(
        'template',
        sa.Column('id', sa.UUID(), nullable=False, comment='Id шаблона'),
        sa.Column('path', sa.String(), nullable=True, comment='Путь до шаблона'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('path'),
        schema='events_admin',
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('template', schema='events_admin')
    # ### end Alembic commands ###
