"""002_favfilm

Revision ID: dd87be929be5
Revises: e3cde4500b03
Create Date: 2025-05-28 07:55:53.851473

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd87be929be5'
down_revision: Union[str, None] = 'e3cde4500b03'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pin_film',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('film_id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('user_id', 'film_id')
    )
    op.create_index(op.f('ix_pin_film_user_id'), 'pin_film', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pin_film_user_id'), table_name='pin_film')
    op.drop_table('pin_film')
    # ### end Alembic commands ###
