"""initial_na

Revision ID: fc93551d3a04
Revises: 
Create Date: 2025-04-30 12:42:40.789493

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc93551d3a04'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE SCHEMA IF NOT EXISTS notification_api")
    op.create_table('event',
    sa.Column('id', sa.UUID(), nullable=False, comment='Id шаблона'),
    sa.Column('title', sa.String(), nullable=False, comment='Название события'),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('type', sa.Enum('regular', 'instance', name='eventtype'), nullable=False),
    sa.Column('roles', sa.JSON(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('template_id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='notification_api'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('event', schema='notification_api')
    op.execute("DROP SCHEMA IF NOT EXISTS notification_api")
    # ### end Alembic commands ###
